using System.Collections.Generic;

namespace Hollowfen
{
    // Placeholder LUT — looks up player-facing strings by ID. Real translation
    // (English + Simplified Chinese for EA) replaces this dictionary later.
    public static class Localization
    {
        private static readonly Dictionary<string, string> _table = new Dictionary<string, string>
        {
            // Main menu
            { "ui.menu.quit_title",   "Quit Hollowfen?" },
            { "ui.menu.quit_message", "Any unsaved progress will be lost." },

            // Field journal family (Story / Field Guide / Wren)
            { "journal.eyebrow",                  "Wren's Field Journal" },
            { "journal.close",                    "Close" },
            { "journal.back",                     "Back" },
            { "journal.previous",                 "Previous" },
            { "journal.next",                     "Next" },
            { "journal.page",                     "{0} of {1}" },
            { "journal.hint.index",               "D-Pad / Stick — browse     A — open     B — back" },
            { "journal.hint.reader",              "Left / Right — turn entry     A — annotations     B — back" },
            { "journal.hint.specimen",            "Drag / R-Stick — rotate     Wheel / LT-RT — zoom     B — back" },
            { "journal.hint.wren",                "D-Pad / L-Stick — browse     Drag / R-Stick — turn Wren     Wheel / LT-RT — zoom     B — back" },
            { "journal.story.title",              "Story" },
            { "journal.story.counter",            "{0} of {1} memories recorded. Hollowfen as Wren lives it." },
            { "journal.story.cards",              "{0} cards" },
            { "journal.story.locked",             "Locked memory" },
            { "journal.story.locked_title",       "· · ·" },
            { "journal.story.locked_body",        "A memory yet to be made." },
            { "journal.story.annotations",        "Wren's annotations" },
            { "journal.story.hide_annotations",   "Hide annotations" },
            { "journal.story.no_note",            "No annotation recorded." },
            { "journal.story.toast_added",         "Story added" },
            { "journal.story.toast_hint",          "Recorded in Wren's journal" },
            { "journal.field.title",              "Mushroom Field Guide" },
            { "journal.field.counter",            "{0} of {1} species recorded. Open a specimen for identification notes." },
            { "journal.field.unknown",            "Unknown specimen" },
            { "journal.field.unknown_label",      "Unknown" },
            { "journal.field.missing_photo",      "No field sketch recorded" },
            { "journal.field.model_pending",      "Three-dimensional study pending" },
            { "journal.field.model_caption",      "Drag to rotate · Scroll to zoom · R to reset" },
            { "journal.field.model_badge",        "3D study" },
            { "journal.field.photo_heading",      "Field photo" },
            { "journal.field.features",           "Identifying features" },
            { "journal.field.note",               "Forager's note" },
            { "journal.field.habitat",            "Habitat" },
            { "journal.field.season",             "Season" },
            { "journal.field.lookalikes",         "Look-alikes" },
            { "journal.field.photo_credit",       "Field image · {0}" },
            { "journal.wren.title",               "Wren" },
            { "journal.wren.background",          "Background" },
            { "journal.wren.perspective",         "How she sees the world" },
            { "journal.wren.carries",             "She carries" },
            { "journal.wren.studies",             "Field studies · Character plates" },
            { "journal.wren.age",                 "Age" },
            { "journal.wren.home",                "Home" },
            { "journal.wren.work",                "Work" },
            { "journal.wren.keepsake",            "Keepsake" },
            { "journal.wren.model_badge",         "Living character study" },
            { "journal.wren.model_caption",       "Drag to turn · Scroll to draw closer · R to reset" },
            { "journal.wren.model_pending",       "Three-dimensional study pending" },
            { "journal.wren.plate.study",         "Plate I · Working study" },
            { "journal.wren.plate.front",         "Plate II · Front" },
            { "journal.wren.plate.back",          "Plate III · Back" },
            { "journal.wren.plate.three_quarter", "Plate IV · Three-quarter" },
            { "journal.wren.plate.knife",         "Plate V · The forager's knife" },

            // Pause menu
            { "ui.pause.eyebrow",     "Hollowfen" },
            { "ui.pause.title",       "Paused" },
            { "ui.pause.resume",      "Resume" },
            { "ui.pause.story",       "Story" },
            { "ui.pause.field_guide", "Field Guide" },
            { "ui.pause.purse",       "Wren's Purse" },
            { "ui.pause.purse_balance", "Wren's Purse  ·  {0}" },
            { "ui.pause.settings",    "Settings" },
            { "ui.pause.save",        "Save Game" },
            { "ui.pause.quit",        "Quit to Main Menu" },
            { "ui.pause.hint",        "Esc / B — resume" },
            { "ui.pause.quit_title",   "Quit to Main Menu?" },
            { "ui.pause.quit_message", "Any unsaved progress will be lost. Save before quitting if you want to keep where you are." },

            // Wren's purse — balance, recent activity, and merchant-aware pouch sales.
            { "purse.title",                    "Wren's Purse" },
            { "purse.eyebrow",                 "Coin & trade ledger" },
            { "purse.silver",                  "Silver" },
            { "purse.copper",                  "Copper" },
            { "purse.balance_heading",         "Current balance" },
            { "purse.total",                   "{0} copper in all" },
            { "purse.conversion",              "Twelve copper make one silver." },
            { "purse.activity",                "Recent activity" },
            { "purse.activity.empty",          "No recent entries in this ledger." },
            { "purse.balance_after",           "Balance · {0}" },
            { "purse.pouch",                   "Mushroom pouch" },
            { "purse.pouch.count",             "{0} specimens carried" },
            { "purse.pouch.empty",             "The pouch is empty." },
            { "purse.quote",                   "{0} would buy {1} for {2}" },
            { "purse.quote.none",              "{0} would not buy anything currently carried" },
            { "purse.sell.nearby",             "{0} is close enough to trade." },
            { "purse.sell.away",               "Speak with Marra at the Crooked Pintle or Theo at his wagon to sell from the pouch." },
            { "purse.sell.button",             "Sell {0} to {1}  ·  +{2}" },
            { "purse.sell.complete",           "Sold {0} from the pouch for {1}. {2} stayed behind." },
            { "purse.sell.refused",            "This buyer wants none of the mushrooms currently carried." },
            { "purse.close",                   "Close purse" },
            { "purse.hint",                    "P / L3 — purse     Esc / B — close" },
            { "purse.transaction.earned",      "Coin earned" },
            { "purse.transaction.spent",       "Coin spent" },
            { "purse.transaction.delivery",    "Village delivery" },
            { "purse.transaction.dialogue",    "A promise paid" },
            { "purse.transaction.marra_sale",  "Mushrooms sold to Marra" },
            { "purse.transaction.theo_sale",   "Mushrooms sold to Theo" },
            { "purse.transaction.purchase",    "Village purchase" },

            // Foraging prompts
            { "prompt.forage.verb",    "Forage" },
            { "prompt.inspect.verb",   "Inspect" },

            // NPC interaction prompts
            { "prompt.npc.talk",       "Talk to" },
            { "prompt.request.view",   "View order from" },
            { "prompt.request.deliver","Deliver to" },

            // Village requests — illustrated, save-backed orders and medicinal deliveries.
            { "request.kind.kitchen",       "Kitchen order" },
            { "request.kind.medicine",      "Medicinal delivery" },
            { "request.kind.market",        "Trader's order" },
            { "request.kind.gathering",     "Village gathering" },
            { "request.requirements",       "Needed from the basket" },
            { "request.reward.copper",      "Payment · {0}" },
            { "request.reward.story",       "For Hollowfen" },
            { "request.deliver",            "Deliver basket" },
            { "request.missing",            "Still gathering" },
            { "request.talk_instead",       "Talk instead" },
            { "request.leave",              "Leave" },
            { "request.continue",           "Continue" },
            { "request.completed.eyebrow",  "Delivery complete" },
            { "request.completed.title",    "A promise kept" },
            { "request.completed.body",     "The basket is delivered. Wren earns {0}." },
            { "request.completed.story_body","The last ingredient is in place. Hollowfen can carry on." },
            { "request.completed.first",    "They will remember that Wren came through." },
            { "request.completed.repeat",   "Good work still counts, even when it is familiar." },
            { "request.tracker.story",      "Village gathering" },
            { "request.tracker.daily",      "Today's order · Day {0}" },

            { "request.marra.field_basket.title", "A Basket for the Hearth" },
            { "request.marra.field_basket.body",  "Marra needs sturdy common mushrooms for the inn's evening pot." },
            { "request.marra.field_basket.line",  "Field Caps hold their shape. Bring those and one field mushroom, and the rain can keep what it ruined." },
            { "request.marra.goldfoot_stew.title", "Goldfoot Stew" },
            { "request.marra.goldfoot_stew.body",  "A richer supper needs Goldfoot for warmth and Wood Ear for the broth." },
            { "request.marra.goldfoot_stew.line",  "One good Goldfoot, two Wood Ears. That will feed six people and make eight believe it fed them." },
            { "request.marra.woodland_broth.title", "Woodland Broth" },
            { "request.marra.woodland_broth.body",  "Marra is stretching the inn's supper with a clean, woodsy broth." },
            { "request.marra.woodland_broth.line",  "An Oyster for body and a Pinecrest for the smell. Fresh, mind you. Broth remembers neglect." },

            { "request.edda.brightspore_draught.title", "Brightspore Draught" },
            { "request.edda.brightspore_draught.body",  "Edda is learning to prepare a careful restorative under Wren's eye." },
            { "request.edda.brightspore_draught.line",  "I checked the page twice. Brightspore for the draught, Wood Ear to settle it. Will you check me a third time?" },
            { "request.edda.wood_ear_poultice.title",   "Wood Ear Poultice" },
            { "request.edda.wood_ear_poultice.body",    "The cottage shelf is short of a simple poultice for winter aches." },
            { "request.edda.wood_ear_poultice.line",    "Two Wood Ears and a Pinecrest. It is not grand medicine, but neither is a sore hand until it is yours." },
            { "request.edda.shelf_tonic.title",         "Tonic for the Shelf" },
            { "request.edda.shelf_tonic.body",          "Edda wants one dependable bottle ready before anyone needs it." },
            { "request.edda.shelf_tonic.line",          "Oyster and Wood Ear keep well together. I want the remedy waiting before the cough arrives." },

            { "request.theo.moss_road_crate.title", "The Moss-Road Crate" },
            { "request.theo.moss_road_crate.body",  "Theo has buyers farther down the road for a small crate of woodland produce." },
            { "request.theo.moss_road_crate.line",  "Two Goldfoots and a Pinecrest. I can sell the flavor, the color, and whatever story survives the axle ruts." },
            { "request.theo.inn_cellar_crate.title", "The Inn Cellar Crate" },
            { "request.theo.inn_cellar_crate.body",  "A roadside kitchen wants reliable mushrooms that will travel without complaint." },
            { "request.theo.inn_cellar_crate.line",  "Oysters and field mushrooms. Nothing romantic. Reliable goods are how romantic traders stay fed." },
            { "request.theo.rain_market_crate.title", "The Rain-Market Basket" },
            { "request.theo.rain_market_crate.body",  "Theo can fill an ordinary market order before the weather turns." },
            { "request.theo.rain_market_crate.line",  "Two Field Caps, one Wood Ear. Modest cargo, honest coin, and no lord's seal anywhere near it." },

            { "request.festival.four_dishes.title", "Four Dishes for the Square" },
            { "request.festival.four_dishes.body",  "Marra has named the four festival dishes: Goldfoot stew, Lacewig broth, Field Cap cakes, and Brightspore tonic." },
            { "request.festival.four_dishes.line",  "One sound specimen for each dish. Bring me the four together, and I will make the square smell alive again." },

            // NPC display names
            { "npc.bram.name",         "Bram" },
            { "npc.marra.name",        "Marra" },
            { "npc.edda.name",         "Edda" },
            { "npc.almy.name",         "Sister Almy" },
            { "npc.joren.name",        "Joren" },
            { "npc.voss.name",         "Voss" },
            { "npc.theo.name",         "Theo" },
            { "npc.calden.name",       "Father Calden" },
            { "npc.hollin.name",       "Hollin" },
            { "npc.pell.name",         "Elder Pell" },
            { "npc.aldric.name",       "Lord Aldric" },

            // Quest objective + display strings (Act I)
            { "quest.arrive.name",       "Homecoming" },
            { "quest.arrive.objective",  "Follow the road to the well in the village square." },
            { "quest.speakBram.name",       "The Crooked Pintle" },
            { "quest.speakBram.objective",  "Speak with Old Bram at the well." },
            { "quest.searchMill.name",      "Your Father's Mill" },
            { "quest.searchMill.objective", "Enter the mill and search the house." },
            { "quest.findJournal.name",      "The Hidden Journal" },
            { "quest.findJournal.objective", "Find Tobin's mushroom journal." },
            // The journal reveal + Tobin's farewell note (Scene 4), read as live serif narration captions.
            // Blank lines split it into caption beats (QuestInteractable._playsNarrationId → NarrationOverlay).
            { "act1.hidden_journal.tobin_note",
              "The first pages were recipes, in her mother's hand.\n\n" +
              "Then Tobin's writing began.\nField Cap. Wood Ear. Pinecrest.\n\n" +
              "Each a careful sketch, and under one a line pressed so hard the pencil tore the paper: never eat what you cannot name twice.\n\n" +
              "If you're reading this, I never told you.\n\n" +
              "The forest was always our family's secret. Your grandmother knew. Your mother knew. I was waiting until you were old enough.\n\n" +
              "I am sorry I waited too long.\n— Da\n\n" +
              "Da." },
            { "quest.firstForage.name",      "The First Forage" },
            { "quest.firstForage.objective", "Gather the three safe basics and the gold-stemmed find at the Old Wood edge." },
            { "quest.firstSale.name",      "Marra's Kitchen" },
            { "quest.firstSale.objective", "Bring your first basket to The Crooked Pintle and see if Hollowfen still has an appetite." },
            { "story.marra_kitchen.interstitial", "An hour later, the inn smelled like Wren's mother. Not exactly. Nothing was exact after enough years." },
            { "quest.meetAlmy.name",      "A Knock at the Door" },
            { "quest.meetAlmy.objective", "Someone is waiting at the mill door." },

            // Quest objective + display strings (Act II)
            { "quest.almyTeach.name",       "The Vine-Tender's Lessons" },
            { "quest.almyTeach.objective",  "Learn cultivation from Sister Almy, then plant Wood Ear spawn in a mill-yard grow bed." },
            { "quest.forgeKnife.name",      "Joren's Forge" },
            { "quest.forgeKnife.objective", "Commission a proper foraging knife from Joren in the walled town — and come back for it tomorrow." },
            { "quest.firstTax.name",        "Twelve Silver by Yule" },
            { "quest.firstTax.objective",   "Earn twelve silver and pay Master Voss at the market square before sundown." },
            { "quest.theoTrade.name",       "The Trader's Ledger" },
            { "quest.theoTrade.objective",  "Theo's wagon comes with the dawn. Bring him a basket worth a ledger line." },
            { "quest.edsGrandfather.name",      "Brightspore at the Bedside" },
            { "quest.edsGrandfather.objective", "Edda waits by the mill. Find Brightspore at the old birch, have Marra make the tonic, and carry it to her grandfather." },
            { "quest.meetHollin.name",       "A Stranger at the Inn" },
            { "quest.meetHollin.objective",  "A traveler at The Crooked Pintle asked for the goldfoot girl by name. Sit with her." },
            { "quest.cottagesReopen.name",       "Two Boards Come Down" },
            { "quest.cottagesReopen.objective",  "Elder Pell keeps the ledger at the village well. Fund the shutters and see two cold cottages open their windows." },
            { "quest.caldenWarning.name",       "Father Calden's Doubt" },
            { "quest.caldenWarning.objective",  "Father Calden has come to the mill and refused tea. Hear him out, then see what he has done to the chapel garden gate." },

            // Quest objective + display strings (Act III)
            { "quest.hollinReveals.name",       "Hollin's Inheritance" },
            { "quest.hollinReveals.objective",  "Hollin waits at the mill with a page folded into oilcloth. Hear the name her grandmother left her." },
            { "quest.findWitchCottage.name",       "The Witch's Cottage" },
            { "quest.findWitchCottage.objective",  "Follow the old path into the Deep Wood and find Sable's cottage. Read what she left on the table." },
            { "quest.wendlightFound.name",       "The Wend's True Course" },
            { "quest.wendlightFound.objective",  "Wendlight grows where water was betrayed. Walk the dry riverbed, follow the pale shine, and find what waits at the bend." },
            { "quest.caldenReconcile.name",      "The Chapel Garden Opens" },
            { "quest.caldenReconcile.objective", "Bring the Wendlight truth to Father Calden. Give him a day with the old registers, then meet him at the chapel garden gate." },
            { "quest.eddaApprentice.name",       "Edda Asks" },
            { "quest.eddaApprentice.objective",  "Edda is waiting at the mill door with a speech she has practiced. Hear her out." },
            { "quest.theoCapitalOffer.name",     "Theo's Capital" },
            { "quest.theoCapitalOffer.objective","Theo has an offer to make. Find him at his wagon, hear him out, ask what you like, and leave when you are ready." },
            { "quest.festivalHosted.name",       "The First Festival in Three Years" },
            { "quest.festivalHosted.objective",  "Speak with Marra, then gather Goldfoot, Lacewig, Field Cap, and Brightspore for the four festival dishes." },
            { "quest.aldricLetter.name",         "A Sealed Letter" },
            { "quest.aldricLetter.objective",    "Voss is waiting with something he was told to deliver in person. Hear him out." },
            { "quest.aldricOfferRead.name",      "The Lord's Offer" },
            { "quest.aldricOfferRead.objective", "Lord Aldric's letter is still sealed on the mill table. Read it by candlelight." },
            { "quest.wendSource.name",           "The Source of the Wend" },
            { "quest.wendSource.objective",      "The Wendlight traced a line upstream. Follow it past the Old Wend to whatever broke the river." },
            { "quest.meetAldric.name",           "The Meeting" },
            { "quest.meetAldric.objective",      "Take the Aldermark and the truth east, to Lord Aldric's manor. Hear his offer, and answer it." },
            { "item.aldric_letter.name",         "Lord Aldric's Letter" },

            // Mushroom tier display names (locked draft 2026-07-11 — QUESTIONS.md Q1; not yet rendered anywhere)
            { "tier.t1.name", "Basket Common" },
            { "tier.t2.name", "Knifework" },
            { "tier.t3.name", "Yard-Grown" },
            { "tier.t4.name", "Deepwood" },

            // Settings screen (batch-28 rebuild — every label localized)
            { "settings.eyebrow",              "Options" },
            { "settings.title",                "Settings" },
            { "settings.tab.audio",            "Audio" },
            { "settings.tab.graphics",         "Graphics" },
            { "settings.tab.controls",         "Controls" },
            { "settings.tab.credits",          "Credits" },
            { "settings.audio.master",         "Master" },
            { "settings.audio.music",          "Music" },
            { "settings.audio.sfx",            "SFX" },
            { "settings.audio.ambience",       "Ambience" },
            { "settings.graphics.fullscreen",  "Fullscreen" },
            { "settings.graphics.resolution",  "Resolution" },
            { "settings.graphics.quality",     "Quality" },
            { "settings.value.on",             "On" },
            { "settings.value.off",            "Off" },
            { "settings.controls.sensitivity", "Look Sensitivity" },
            { "settings.controls.action",      "Action" },
            { "settings.controls.gamepad",     "Gamepad" },
            { "settings.controls.keyboard",    "Keyboard" },
            { "settings.controls.section.ui",       "UI" },
            { "settings.controls.section.player",   "Player" },
            { "settings.controls.section.dialogue", "Dialogue" },
            { "settings.hint",                 "Q · E  or  LB · RB — switch tabs        Esc / B — back" },
            { "settings.quality.pc",           "PC" },   // display name for the project's sole quality level (row hidden until a 2nd exists)

            // Binding reference table (kept in sync with the project InputActions asset)
            { "settings.bind.navigate",     "Navigate" },
            { "settings.bind.navigate.pad", "D-Pad / Left Stick" },
            { "settings.bind.navigate.kb",  "W A S D / Arrows" },
            { "settings.bind.submit",       "Submit" },
            { "settings.bind.submit.pad",   "A / Cross" },
            { "settings.bind.submit.kb",    "Enter / Space" },
            { "settings.bind.cancel",       "Cancel" },
            { "settings.bind.cancel.pad",   "B / Circle" },
            { "settings.bind.cancel.kb",    "Esc" },
            { "settings.bind.tabLeft",      "Tab Left" },
            { "settings.bind.tabLeft.pad",  "LB / L1" },
            { "settings.bind.tabLeft.kb",   "Q" },
            { "settings.bind.tabRight",     "Tab Right" },
            { "settings.bind.tabRight.pad", "RB / R1" },
            { "settings.bind.tabRight.kb",  "E" },
            { "settings.bind.delete",       "Delete" },
            { "settings.bind.delete.pad",   "X / Square" },
            { "settings.bind.delete.kb",    "Delete" },
            { "settings.bind.move",         "Move" },
            { "settings.bind.move.pad",     "Left Stick" },
            { "settings.bind.move.kb",      "W A S D" },
            { "settings.bind.look",         "Look" },
            { "settings.bind.look.pad",     "Right Stick" },
            { "settings.bind.look.kb",      "Mouse" },
            { "settings.bind.interact",     "Interact" },
            { "settings.bind.interact.pad", "Y / Triangle" },
            { "settings.bind.interact.kb",  "E" },
            { "settings.bind.jump",         "Jump" },
            { "settings.bind.jump.pad",     "A / Cross" },
            { "settings.bind.jump.kb",      "Space" },
            { "settings.bind.satchel",      "Satchel" },
            { "settings.bind.satchel.pad",  "X / Square" },
            { "settings.bind.satchel.kb",   "I" },
            { "settings.bind.journal",      "Mushroom Field Guide" },
            { "settings.bind.journal.pad",  "D-Pad Up" },
            { "settings.bind.journal.kb",   "J" },
            { "settings.bind.map",          "Map" },
            { "settings.bind.map.pad",      "Touchpad / View" },
            { "settings.bind.map.kb",       "M" },
            { "settings.bind.pause",        "Pause" },
            { "settings.bind.pause.pad",    "Start / Options" },
            { "settings.bind.pause.kb",     "Esc" },
            { "settings.bind.advance",      "Advance" },
            { "settings.bind.advance.pad",  "A / Cross" },
            { "settings.bind.advance.kb",   "Space / Enter" },
            { "settings.bind.skip",         "Skip" },
            { "settings.bind.skip.pad",     "B / Circle" },
            { "settings.bind.skip.kb",      "Esc" },
            { "settings.bind.choices",      "Choices 1-4" },
            { "settings.bind.choices.pad",  "D-Pad up/right/down/left" },
            { "settings.bind.choices.kb",   "1 / 2 / 3 / 4" },

            // First-steps intro guide (batch-30). Passage = bible Act I Scene 1 transposed to
            // Wren's first-person journal present (no invented facts); hints verified against
            // the shipped HUD/compass/bindings.
            // Confirm modal (batch-44 parchment restyle)
            { "confirm.cancel",     "Cancel" },
            { "confirm.confirm",    "Confirm" },
            { "confirm.hint",       "Esc — cancel" },

            { "guide.eyebrow",      "Act I · Homecoming" },
            { "guide.status",       "New objective" },
            { "guide.title",        "Into the Village" },
            { "guide.passage",      "The square is just down the road, the old well standing at the heart of it. I'll find Old Bram there — he keeps The Crooked Pintle, and he holds my father's mill key." },
            { "guide.task_label",   "Current objective" },
            { "guide.hint.compass", "Follow the road down into the square — the compass ribbon marks the well." },
            { "guide.hint.ribbon",  "Old Bram is by the well — walk up and Interact to speak with him." },
            { "guide.hint.journal", "J or D-Pad Up opens the Mushroom Field Guide. Esc or Options opens Wren's full journal menu." },
            { "guide.ctl.move",     "Move" },
            { "guide.ctl.look",     "Look" },
            { "guide.ctl.interact", "Interact" },
            { "guide.ctl.satchel",  "Satchel" },
            { "guide.ctl.map",      "Map" },
            { "guide.ctl.journal",  "Mushroom Field Guide" },
            { "guide.key.wasd",     "W A S D" },
            { "guide.key.lstick",   "Left Stick" },
            { "guide.key.mouse",    "Mouse" },
            { "guide.key.rstick",   "Right Stick" },
            { "guide.key.e",        "E" },
            { "guide.key.y",        "Y" },
            { "guide.key.j",        "J" },
            { "guide.key.x",        "X" },
            { "guide.key.m",        "M" },
            { "guide.key.select",   "Select" },
            { "guide.key.esc",      "Esc" },
            { "guide.key.start",    "Start" },
            { "guide.button",       "Set out →" },
            { "guide.dismiss_hint", "Enter / A" },
            { "guide.footer",       "J / D-Pad Up · Mushroom Field Guide" },

            // Credits (shipped copy verbatim — final credits copy is Trevor's open backlog item)
            { "credits.heading",   "HOLLOWFEN — THE FAILING VILLAGE" },
            { "credits.sub",       "An exploration & foraging story by Trevor Kist." },
            { "credits.build",     "Built with Unity 6 · ScriptableObject-driven content · Steam Deck-ready" },
            { "credits.copyright", "Story, dialogue, characters © Trevor Kist" },
            { "credits.photos",    "Mushroom photographs courtesy Wikimedia Commons under CC licenses." },
            { "credits.wren",      "Wren character art generated for production use." },
            { "credits.engine",    "Engine built on Unity Starter Assets, Magic Pig Games, NatureManufacture." },
            { "credits.fonts",     "Typeset in IM Fell English and EB Garamond (SIL Open Font License)." },
            { "credits.thanks",    "Thanks for walking back into Hollowfen with Wren." },

            // Ending flow
            { "ending.choice.speaker",   "Hollowfen's future" },
            { "ending.save.complete",    "Story complete — Hollowfen's future chosen" },
            { "ending.credits.eyebrow",  "A future chosen" },
            { "ending.credits.saved",    "Ending recorded in Wren's journal · Game saved" },
            { "ending.credits.heading",  "Hollowfen will remember" },
            { "ending.credits.return",   "Return to Main Menu" },
            { "ending.credits.remain",   "Remain in Hollowfen" },
            { "ending.credits.hint",     "You may keep walking after the story ends." },

            // Cultivation
            { "prompt.plant.verb", "Plant" },
            { "growbed.name",      "Grow Bed" },

            // Interaction verbs (doors, props)
            { "prompt.door.unlock",  "Unlock" },
            { "prompt.examine.verb", "Examine" },
            { "prompt.journal.read", "Read" },
            { "prompt.deliver.verb", "Deliver tonic to" },

            // Inspect screen
            { "inspect.unknown.eyebrow", "UNKNOWN" },
            { "inspect.unknown.title",   "?" },
            { "inspect.unknown.body",    "A mushroom you haven't catalogued. Forage one to learn more." },
            { "inspect.locked.knowledge", "The journal has not taught Wren how to harvest this species safely." },
            { "prompt.rest.verb", "Rest" },
            { "rest.mill_hearth.name", "by the mill hearth" },
            { "rest.confirm.dusk.title", "Wait Until Dusk?" },
            { "rest.confirm.dusk.body", "Pass the afternoon at the mill. Time, crops, and village obligations will move forward." },
            { "rest.confirm.dawn.title", "Rest Until Dawn?" },
            { "rest.confirm.dawn.body", "Sleep until morning. Time, crops, and village obligations will move forward." },
            { "rest.transition.dusk", "Day {0} · Dusk" },
            { "rest.transition.dawn", "Day {0} · Dawn" },
            { "cultivation.eyebrow", "MILL YARD · CULTIVATION" },
            { "cultivation.title", "Choose Spawn" },
            { "cultivation.recipe.details", "Basket {0}   ·   {1:0.#}h   ·   Yield {2}" },
            { "cultivation.cancel", "Leave the bed empty" },
            { "inspect.btn.forage",      "Prepare to Cut" },
            { "inspect.btn.leave",       "Leave" },

            // Cinematic mushroom-cutting challenge
            { "forage.cut.title",                 "Knife Work · {0}" },
            { "forage.cut.brace_label",           "Brace" },
            { "forage.cut.saw_label",             "Saw" },
            { "forage.cut.instruction.gamepad",   "Steady the stem, then make level alternating strokes." },
            { "forage.cut.instruction.keyboard",  "Hold S to steady the stem, then alternate A and D." },
            { "forage.cut.hint.gamepad",          "Left Stick DOWN · hold steady     Right Stick LEFT / RIGHT · saw     B / Circle · cancel" },
            { "forage.cut.hint.keyboard",         "Hold S · steady     Alternate A / D · saw     Esc · cancel" },
            { "forage.cut.status.brace",          "Brace the stem" },
            { "forage.cut.status.ready",          "Stem steady · begin the cut" },
            { "forage.cut.status.angle",          "Keep the blade level" },
            { "forage.cut.status.rhythm",         "Good rhythm" },
            { "forage.cut.status.clean",          "Clean cut" },
            { "forage.cut.strokes",               "Cut progress · {0} / {1}" },
            { "forage.cut.collected",             "{0} added to Wren's satchel." },
            { "forage.cut.release",               "Specimen secured" },

            // Inventory screen
            { "inventory.empty",     "Your pouch is empty. Forage some mushrooms in the woods." },
            { "inventory.btn.close", "Close" },
            { "inventory.keepsakes", "KEEPSAKES" },

            // Key items
            { "toast.received",             "Received" },
            { "item.mill_key.name",         "Mill Key" },
            { "item.fathers_journal.name",  "Father's Journal" },
            { "item.sealed_letter.name",    "Sealed Letter" },
            { "item.forage_knife.name",     "Horn-Handled Foraging Knife" },
            { "item.brightspore_tonic.name", "Brightspore Tonic" },
            { "item.seedbook.name",          "Sable's Seedbook" },

            // Map locations (POIs)
            { "loc.fathers_mill.name",   "Father's Mill" },
            { "loc.village_well.name",   "Village Well" },
            { "loc.crooked_pintle.name", "The Crooked Pintle" },
            { "loc.marra_kitchen.name",  "Marra's Kitchen" },
            { "loc.almy_doorway.name",   "Almy's Doorway" },
            { "loc.jorens_forge.name",   "Joren's Forge" },
            { "loc.chapel.name",         "Chapel" },
            { "loc.old_wood_edge.name",  "Old Wood Edge" },
            { "loc.theos_wagon.name",    "Theo's Wagon" },
            { "loc.eddas_cottage.name",  "Edda's Cottage" },
            { "loc.witchs_cottage.name", "The Witch's Cottage" },
            { "loc.old_wend.name",       "The Old Wend" },
            { "loc.clear_cut.name",      "The Clear-Cut" },
            { "loc.manor.name",          "Aldric's Manor" },

            // World regions — shared by map chrome and the non-blocking arrival title.
            { "region.arrival.eyebrow",  "Entering" },
            { "region.village.name",     "Hollowfen Village" },
            { "region.village.subtitle", "Hearthlight, rain, and familiar roads." },
            { "region.wend.name",        "The Wend" },
            { "region.wend.subtitle",    "The old watercourse through wet earth and stone." },
            { "region.old_wood.name",    "The Old Wood" },
            { "region.old_wood.subtitle","Where the footpath thins beneath the canopy." },
            { "region.manor.name",       "Aldric's Manor" },
            { "region.manor.subtitle",   "High walls above the failing village." },

            // Map location short descriptions (side panel copy)
            { "loc.fathers_mill.desc",   "The old water mill where Wren grew up. The wheel still turns; the stones lie idle." },
            { "loc.clear_cut.desc",      "Upstream of the Old Wend: stumps, drag-trails, a cold camp, and the throttled spring. This is what broke the river." },
            { "loc.village_well.desc",   "The heart of the village. Buckets at dawn, gossip at dusk." },
            { "loc.crooked_pintle.desc", "Hollowfen's only tavern. Cheap ale, warmer fires." },
            { "loc.marra_kitchen.desc",  "Marra cooks for everyone. The smell of broth never quite leaves the air." },
            { "loc.almy_doorway.desc",   "Sister Almy's threshold. The seedbook lives somewhere within." },
            { "loc.jorens_forge.desc",   "Joren's hammer rings before dawn. He shapes more than iron." },
            { "loc.chapel.desc",         "Father Calden tends the chapel. Quiet, mostly empty, always open." },
            { "loc.old_wood_edge.desc",  "Where the village footpath ends and the Old Wood begins." },
            { "loc.theos_wagon.desc",    "Theo's board and ledger. He pays more than Bram could, less than the Capital would, and says both plainly." },
            { "loc.eddas_cottage.desc",  "A low cottage near the mill. Edda's grandfather keeps to his bed by the window." },
            { "loc.witchs_cottage.desc", "One room where the Deep Wood gathers around a spring. Sable's door opens for those who enter kindly." },
            { "loc.old_wend.desc",       "The river's abandoned course — rounded stones, grass fingers, and a thin watery shine at dawn." },
            { "loc.manor.desc",          "Lord Aldric's estate, east of the village: oak panelling, poured tea, and ledgers where other people keep guilt." },

            // Map side panel labels
            { "map.eyebrow.landmark",     "LANDMARK" },
            { "map.eyebrow.waypost",      "WAYPOST" },
            { "map.eyebrow.unknown",      "UNDISCOVERED" },
            { "map.unknown.title",        "An unfamiliar place" },
            { "map.unknown.body",         "You've heard of this place, but haven't been there. Visit to learn more." },
            { "map.placeholder.title",    "Hollowfen" },
            { "map.placeholder.body",     "Select a landmark to read its entry. Use the arrow keys, D-pad, or click a pin." },
            { "map.btn.waypoint",         "Set Waypoint" },
            { "map.btn.waypoint_clear",   "Clear Waypoint" },
            { "map.btn.waypoint_disabled","Visit first to set waypoint" },
            { "map.label.distance",       "DISTANCE" },
            { "map.label.region",         "REGION" },
            { "map.current_location",     "YOU ARE HERE" },
        };

        public static string Get(string stringId)
        {
            if (string.IsNullOrEmpty(stringId)) return stringId;
            return _table.TryGetValue(stringId, out var s) ? s : stringId;
        }

        // Incremental localization seam for data-authored copy. Every displayed
        // value still passes through the LUT, while English ScriptableObject copy
        // remains a safe fallback until its translation row is populated.
        public static string Get(string stringId, string englishFallback)
        {
            if (string.IsNullOrEmpty(stringId)) return englishFallback ?? "";
            return _table.TryGetValue(stringId, out var s) ? s : (englishFallback ?? stringId);
        }
    }
}
